# Generated by Django 3.1.7 on 2022-02-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibkr', '0014_group_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='cost',
            field=models.DecimalField(decimal_places=4, max_digits=16, null=True),
        ),
    ]
